### ISSUE TITLE
Datasets and files to ignore

### ISSUE THREAD

**Issue by sarahcd** [peterdesmet/movebank2gbif#10]
1. As discussed earlier, I think we want to exclude datasets where the reference data file contains 'manipulation-type' values other than "none" (stored in the reference data file)—in these cases the animals may have been physiologically manipulated or translocated, e.g. for an experiment, and I don't think it would make sense to store them in GBIF.

2. There are data files without reference data or location data that store light-levels or other sensor measurements that do not have corresponding locations for the same timestamps. These files/datasets won't have 'location-long' or 'location-lat'.

**Comment by peterdesmet** [comment]
Since we don't publish all datasets as part of MOVE2GBIF, this decisions can be made on a dataset to dataset basis.
