### ISSUE TITLE
Mapping deployment-level values to time-location records

### ISSUE THREAD

**Issue by sarahcd** [peterdesmet/movebank2gbif#11]
In https://github.com/peterdesmet/movebank2gbif/blob/master/mapping.md (see #5 ) I commented on several cases where information is stored in the "reference data" file and is relevant only for a deployment, meaning that in cases the same animal was tracked by multiple deployments, the age of the animal or the tag information stored in samplingProtocol could have different values for each deployment. The relevant variables needed to put this information all in 1 record are:
        data file: tag-local-identifier, individual-local-identifier, timestamp
        reference data file: tag-id, animal-id, deploy-on-date, deploy-off-date, (also deployment-id)
tag-id = tag-local-identifier
animal-id = individual-local-identifier

The attached files show just a few records that provide an example of an animal with multiple deployments and also a marked outlier. I changed a couple of values from the original to make the example clearer.
[data-deployments-outliers-example.zip](https://github.com/peterdesmet/movebank2gbif/files/807544/data-deployments-outliers-example.zip)

**Comment by peterdesmet** [comment]
This is now covered in https://github.com/inbo/movepub, deployment remarks and e.g. sex are only applied to that deployment.
