### ISSUE TITLE
Get data URL

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/movebank2gbif#3]
I have no info in the [metadata I got from DataCite](https://github.com/peterdesmet/movebank2gbif/blob/master/data/datasets.csv) regarding the URLs of the data + metadata files themselves (e.g. https://www.datarepository.movebank.org/bitstream/handle/10255/move.431/README.txt?sequence=2)

@sarahcd, is their a Movebank Repo service that I can feed with a DOI and get those file URLs back? If not, we'll have to crawl those pages (which can work fine, but is potentially less stable).

**Comment by sarahcd** [comment]
Yes, it looks like we can do this using documentation at http://wiki.datadryad.org/Data_Access. I did not test this extensively or through everything described here, but here are 2 options that look like they should work. Note the readmes are automatically, always titled "README.txt".
1. request METS format: https://www.datarepository.movebank.org/metadata/handle/10255/move.###/mets.xml
   The related DOI is under "identifier" mdschema="dc". The URLs for the main file and readme are under mets:FLocat LOCTYPE="URL". You need to add "https://www.datarepository.movebank.org" to the beginning to get the full URLs.
   example: https://www.datarepository.movebank.org/metadata/handle/10255/move.503/mets.xml
2. use OAI-PMH protocol, GetRecord: https://www.datarepository.movebank.org/oai/request?verb=GetRecord&identifier=oai:www.datarepository.movebank.org:10255/move.###&metadataPrefix=mets
   The related DOI is under "mods:identifier", mods:relatedItem type="host". The complete URLs for the main file and readme are under FLocat LOCTYPE="URL"
   example: https://www.datarepository.movebank.org/oai/request?verb=GetRecord&identifier=oai:www.datarepository.movebank.org:10255/move.503&metadataPrefix=mets

A possible missing piece here is a way to map between DOIs and record handles. Let me know if I should look into that further.

**Comment by peterdesmet** [comment]
Way to proceed:
1. Get `handle` from resolved DOI, e.g. http://doi.org/10.5441/001/1.TC76G560 points to https://www.datarepository.movebank.org/handle/10255/move.457. The handle is `move.457`.
2. Use handle to query via METS or OAI-PMH. The latter will return absolute data file URLs, which is more useful. So, https://www.datarepository.movebank.org/oai/request?verb=GetRecord&identifier=oai:www.datarepository.movebank.org:10255/move.457&metadataPrefix=mets
3. In `<fileSec>` get the URL of the data files. Ignore all `README.txt`

Unfortunately, the `<fileSec>` will be empty for a dataset handle ([457](https://www.datarepository.movebank.org/oai/request?verb=GetRecord&identifier=oai:www.datarepository.movebank.org:10255/move.457&metadataPrefix=mets)), so we'll need to get each separate file handle ([458](https://www.datarepository.movebank.org/oai/request?verb=GetRecord&identifier=oai:www.datarepository.movebank.org:10255/move.458&metadataPrefix=mets), [459](https://www.datarepository.movebank.org/oai/request?verb=GetRecord&identifier=oai:www.datarepository.movebank.org:10255/move.459&metadataPrefix=mets), [460](https://www.datarepository.movebank.org/oai/request?verb=GetRecord&identifier=oai:www.datarepository.movebank.org:10255/move.460&metadataPrefix=mets)). Those could be retrieved via `HasPart` in `metadata.relatedIdentifier`.

**Comment by peterdesmet** [comment]
@sarahcd let's examine if there really isn't a way to get the file URLs via DataCite. Probably not, but it would make things more broadly applicable.

**Comment by sarahcd** [comment]
An update on this: It appears it is possible to link directly to data files using custom URLs with the pattern
http://data.datacite.org/MIME_TYPE/DOI 
and can query available media for a DOI with the pattern
https://mds.datacite.org/media/DOI

However, if I understand, the DOI issuer needs to provide the media types and URLs to DataCite in the same way we provide the URL for each DOI's landing page. Currently, we do not provide this information, so this step would need to be built in to our repository software or added manually at https://mds.datacite.org.

More info at
https://data.datacite.org/
https://mds.datacite.org/static/apidoc#tocAnchor-20

**Comment by peterdesmet** [comment]
That would be neat! I tried it for http://doi.org/10.5441/001/1.bs0s09c8/1:

* http://data.datacite.org/txt/10.5441/001/1.bs0s09c8/1: should get README.txt, but says "Requested resource not found"
* https://mds.datacite.org/media/10.5441/001/1.bs0s09c8/1: requires authentication.

The first one is probably because the MIME_TYPE info is not provided and for the second one it's unfortunate authentication is required. Do you know a working - none-Movebank-related - example? I think we should investigate this a bit further before thinking about providing this information from Movebank, assuming it can be done retroactively.

**Comment by sarahcd** [comment]
The example at https://data.datacite.org is 
http://data.datacite.org/application/pdf/10.5284/1015681
to directly access the PDF file published with DOI 10.5284/1015681. The website here requires me to hit "accept" prior to getting the file, so at least for that example there might be an issue trying to automate access even with a direct link.

It looks like the file links can be provided and updated by the issuer anytime at DataCite, the same way that the URLs for the landing pages can; presumably we'd have to add these manually for all existing files. I'm not sure if this would be easier or work better than our existing plan....

**Comment by peterdesmet** [comment]
New implementation Movepub (https://github.com/inbo/movepub) expects datasets to be Frictionless Data Package so data can be found.
