### ISSUE TITLE
Map Movebank data model to Darwin Core occurrence

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/movebank2gbif#5]
We'll describe this mapping in this file: https://github.com/peterdesmet/movebank2gbif/blob/master/mapping.md

@sarahcd, I've already:
- Added all DwC fields + a link to their definition
- Indicated most that are relevant (with `possibly...` and `recommended...`) and should get a mapping
- Which most that are irrelevant: `n/a`
- Some mappings (for record-level terms)

I think it's useful to use the same format for each mapping:
- Title
- Short description
- Example

E.g.:

> #### [license](http://rs.tdwg.org/dwc/terms/index.htm#license)
> 
> All data in the Movebank Data Repository are published under CC0. That information could be retrieved from `metadata.rightsURI`, but it's easier to use the **static value** (with the exact same content):
> 
>    http://creativecommons.org/publicdomain/zero/1.0/

This might serve as an example for the mapping: https://github.com/inbo/data-publication/tree/master/datasets/bird-tracking-gull-occurrences/mapping

**Comment by sarahcd** [comment]
I've started on this and will try to get through it in the next week. Search "SCD" to find my questions or comments where I'm uncertain what to include. Let me know if there is another standard way to include questions/comments or if you notice anything else I should be doing differently in how I'm adding the info! (I don't know much about GitHub standards/etiquette. :))

**Comment by sarahcd** [comment]
I've gotten through a complete first "draft". My main comments/questions:
- The mapping here I think includes all of the most common/important variables we store in Movebank studies (considering these will be going to a biodiversity database), but there are a large number of less commonly used variables. I might think of a few more that should be added as we go on, but for the rest I recommend referring to the complete dataset by DOI in informationWithheld.
- Published datasets include records with no lat/lon (ie a fix could not be obtained) and records marked as outliers. I suggest defining outliers in occurrrenceStatus or georeferenceVerificationStatus. Would it be preferable/possible to exclude these records from GBIF entirely?
- As discussed earlier, I think we want to exclude datasets where the reference data file contains manipulation-type values other than "none"—in these cases the animals may have been physiologically manipulated or translocated, e.g. for an experiment, and I don't think it would make sense to store them in GBIF.
- I've commented on several cases where information is stored in the "reference data" file and is relevant only for a deployment, meaning that in cases the same animal was tracked by multiple deployments, the age of the animal or the tag information stored in samplingProtocol could have different values for each deployment. The relevant variables needed to put this information all in 1 record are:
  - data file: tag-local-identifier, individual-local-identifier, deployment-id, timestamp
  - reference data file: tag-id, animal-id, deploy-on-date, deploy-off-date

The attached files show just a few records that provide an example of an animal with multiple deployments and also a marked outlier. I changed a couple of values from the original to make the example clearer.
[data-deployments-outliers-example.zip](https://github.com/peterdesmet/movebank2gbif/files/765125/data-deployments-outliers-example.zip)

**Comment by peterdesmet** [comment]
Thanks, only seeing this now. Regarding GitHub best practice: the best way to propose important changes is via a [pull request](https://help.github.com/articles/about-pull-requests/). You can start one when you plan to commit stuff:

![screen shot 2017-02-28 at 12 55 27](https://cloud.githubusercontent.com/assets/600993/23404443/584cf9f2-fdb5-11e6-9ea0-5605e3aa8415.png)

That leaves a better trace for reviewing those changes and allows to add comments: https://help.github.com/articles/commenting-on-a-pull-request/

But we'll manage with how things were done now, as we can always see who added what with the blame feature 😄  (button above file): https://github.com/peterdesmet/movebank2gbif/blame/master/mapping.md

What I would like to ask is, if you can [submit your four questions from the previous comment](https://github.com/peterdesmet/movebank2gbif/issues/5#issuecomment-278790656) into separate issues, so we can tackle those one by one?

**Comment by sarahcd** [comment]
Whatever we find that is wrong, I'm sure it's my newbie mistakes, we don't even need the blame button. :) I've figured out how to pull, edit, commit etc using my Terminal, so I think I can do it correctly from now on. The separate issues are on their way....

**Comment by peterdesmet** [comment]
This is now implemented as part of https://github.com/inbo/movepub (function `write_dwc()`).
