### ISSUE TITLE
Get list of datasets

### ISSUE THREAD

**Issue by peterdesmet** [peterdesmet/movebank2gbif#6]
We'll get the list of relevant datasets via DataCite. See https://github.com/peterdesmet/movebank2gbif/blob/master/notebooks/get-movebank-data.ipynb

**Filters to apply**:
1. Search filter: `contributor: "Movebank Data Repository"`. That will exclude some Movebank datasets without metadata, but those are in fact test datasets, that shouldn't have been registered under this DOI domain (see #2)
2. Remove subdirectory DOIs ( `/1`, `/2`), which are the DOIs for files in a package. That way, we only keep DOIs for packages.
3. Search in `metadata.relatedIdentifier` and remove datasets with `IsPreviousVersionOf`. Those are older packages, which have been superceded by newer versions (registered under a new DOI).

That should result in approx. 55 datasets.

**Comment by peterdesmet** [comment]
Turns out Movebank has a new stable API: http://api.datacite.org/ Just tested it. Unfortunately, it doesn't return all relevant metadata anymore (and no csv either, but that's less of a problem). Options:
1. Continue to use the beta API, but that will go away at some point.
2. Venture into querying via OAI-PMH, but that's more complex, e.g. searching doesn't seem very straightforward. 😅 And if we query via OAI, we might as well query the movebank repo directly.
3. Let DataCite know we want the missing metadata attributes (I did via [Twitter](https://twitter.com/peterdesmet/status/758607774964150272)) and wait...

**Comment by sarahcd** [comment]
I've just gotten confirmation from DataCite that the missing metadata will be added, and currently are (somewhat) available through the "XML" field: "This is on our roadmap and we hope to have all metadata in the REST API within the next three months. They are actually in there already, as base64-encoded field "XML", but that requires a bit of extra work."

**Comment by peterdesmet** [comment]
https://github.com/inbo/movepub now offers functionality to convert to Darwin Core, but the MOVE2GBIF project does not have the mission to map all Movebank datasets to GBIF. `wontfix` for now.
