### ISSUE TITLE
Choosing variables to include in GBIF

### ISSUE THREAD

**Issue by sarahcd** [peterdesmet/movebank2gbif#8]
The Movebank contains ~200 data attributes that describe events (stored in the data file, 1 row per tag+timestamp), animals, tags, or deployments (stored in the reference data file, 1 row per deployment). Many of these attributes are used only rarely. The mapping at https://github.com/peterdesmet/movebank2gbif/blob/master/mapping.md now includes the most common/important of these attributes (considering that these will be going to a biodiversity database). I might think of a few more that should be added as we go on, but for the rest I recommend referring to the complete dataset by DOI in informationWithheld.

**Comment by peterdesmet** [comment]
This is also the approach we chose in https://github.com/inbo/movepub
