### ISSUE TITLE
Records that don't represent animal observations

### ISSUE THREAD

**Issue by sarahcd** [peterdesmet/movebank2gbif#9]
Published datasets in Movebank often include records (rows in the data file) that do not represent a location where an animal was observed:
1. Records with no lat/lon because a fix could not be obtained. For these 'location-lat' and 'location-long' will be blank.
2. Records with no lat/lon because the file is for a non-location sensor (like a geolocator). For these 'location-lat' and 'location-long' will be missing from the file entirely.
3. Records marked as outliers. The simplest way to identify these is that 'visible' = FALSE.
4. Pre- or post-deployment records. For these 'individual-local-identifier' is blank. This will only occur rarely; I think none so far include them but we have a dataset in review with data from some undeployed test tags.

I think 1, 2, and 4 could be ignored because they would not result in GBIF records showing animals in places they were not actually observed. Would it be preferable/possible to exclude these records from GBIF entirely?

For 3, we could define outliers in occurrrenceStatus or georeferenceVerificationStatus. Would it be preferable/possible to exclude these records from GBIF entirely?

In the example dataset (10.5441/001/1.sj8t3r11) only 3 is relevant, so we don't necessarily need to find a solution for each of these.

**Comment by peterdesmet** [comment]
In https://github.com/inbo/movepub to exclude all records that have `visible = FALSE`.
